# Generated by Django 4.2.7 on 2023-11-24 14:46

import ZadaniaRekrutacyjne.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ZadaniaRekrutacyjne", "0002_alter_pesel_pesel_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pesel",
            name="pesel_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    ZadaniaRekrutacyjne.validators.validate_pesel,
                    django.core.validators.MinLengthValidator(11),
                ],
            ),
        ),
    ]
