# Generated by Django 4.2.7 on 2023-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ZadaniaRekrutacyjne", "0006_alter_texts_file_alter_texts_scrambled_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="texts",
            name="scrambled_text",
            field=models.CharField(null=True),
        ),
    ]
