# Generated by Django 4.2.7 on 2023-11-25 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ZadaniaRekrutacyjne", "0007_alter_texts_scrambled_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="texts",
            old_name="scrambled_text",
            new_name="shuffled_text",
        ),
    ]
