# Generated by Django 4.2.7 on 2023-11-24 12:54

import ZadaniaRekrutacyjne.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pesel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pesel_number",
                    models.IntegerField(
                        max_length=11,
                        validators=[ZadaniaRekrutacyjne.validators.validate_pesel],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Texts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="text_files")),
                ("scrambled_text", models.CharField(max_length=50)),
            ],
        ),
    ]
