# Generated by Django 4.2.7 on 2023-11-24 12:54

import ZadaniaRekrutacyjne.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ZadaniaRekrutacyjne", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pesel",
            name="pesel_number",
            field=models.IntegerField(
                validators=[ZadaniaRekrutacyjne.validators.validate_pesel]
            ),
        ),
    ]
