# Generated by Django 4.2.7 on 2023-11-24 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ZadaniaRekrutacyjne",
            "0004_pesel_birthdate_pesel_sex_alter_pesel_pesel_number",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pesel",
            new_name="PeselData",
        ),
    ]
